#!/bin/bash

PATH="/bin:/sbin:/usr/bin:/usr/sbin"
export PATH

cmd="$SINGULARITY_NETNS_COMMAND"
pid="$SINGULARITY_NETNS_PID"
ppid="$SINGULARITY_NETNS_PPID"
interface="$SINGULARITY_NETNS_IFNAME"
cnipath="$SINGULARITY_NETNS_CNIPATH"
confdir="$SINGULARITY_NETNS_CONFDIR"
conffile="$SINGULARITY_NETNS_CONF"
conf="$confdir/$conffile"
net_type="$SINGULARITY_NETNS_TYPE"

if [ -z "$cmd" ]; then
    echo "Bad command"
    exit 1
fi

if [ -z "$pid" ]; then
    echo "No pid specified"
    exit 1
fi

export CNI_COMMAND="$cmd"
export CNI_CONTAINERID="$pid"
export CNI_PATH="$cnipath"
export CNI_IFNAME="$interface"

if [ "$ppid" != 0 ]; then
    export CNI_NETNS="/proc/$ppid/ns/net"
else
    export CNI_NETNS="/proc/$pid/ns/net"
fi

$cnipath/$net_type < "$conf" > /dev/null
exit $!
